### ISSUE TITLE
Duplicates in the vacancy roles filter

### ISSUE THREAD

**Issue by franei** [xrnl/extinction-rebellion-nl#100]
Today somebody reported an issue with the filter for vacancy roles, where some workingGroup categories appear twice, and some vacancies slip through the filter. The problem seems to be that some vacancy posts have the `&` character replaced by `&amp;` in the json array. 

Here's why I think this happens:
When someone edits a vacancy in WP using the VISUAL editor, WP replaces the ampersand character inside the json with `&amp;`. This doesn't happen when using the TEXT editor.

One way to prevent this from happening in the future is to disable the VISUAL editor, just for the `volunteer_vacancy` post type.

Adding something like this filter in `functions.php` would do the trick:
```php
    add_filter('user_can_richedit', function( $default ){
      if( get_post_type() === 'volunteer_vacancy') return false;
      return $default;
    });
```

`

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/25393215/97780333-49a33d80-1b84-11eb-9226-62b5d8f66cb8.png">

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/25393215/97780312-36906d80-1b84-11eb-99b0-f11997a5b41b.png">

#### Visual editor disabled:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/25393215/97801318-1de38e80-1c3c-11eb-8877-141d9a75427a.png">

**Comment by SamLubbers** [comment]
@franei great that you identified the source of the problem. A month ago we had the same issue and I had to change the `&` character in the vacancies that had `&amp;`. It would be good to disable the visual editor for this post type so the problem doesn't happen again. If your code snippet works we can add it straight away, but if it will take some time to get this to work I wouldn't bother trying to fix it, because this issue is easy to fix if it happens and (hopefully :crossed_fingers:) we can have the volunteer platform live soon.

**Comment by franei** [comment]
@SamLubbers yes that snippet seems to be working well, It really just disables the visual editor for vacancy posts. So I've just added it to a PR together with some small changes I wanted to make to the local groups custom post type (#101)
