### ISSUE TITLE
Problem with sign-up form on website

### ISSUE THREAD

**Issue by haikomeelis** [xrnl/extinction-rebellion-nl#48]
Good Morning, 

After a talk in Roermond we have been signing up new rebels via a mobile phone. It turns out that this doesn't work as expected. Several problems:
- In Action Network the tag-field Roermond Email List is not set anymore. This used to be the case. This tag is used to send email to - for example - Roermond only. This means that we need add this tag to all new signed up rebels and this is also problematic as many reporting functions on Action Network have been disabled suddenly so it has been made difficult to select recently signed up rebels in Roermond. Really unhappy with this.
- Instead local_group was set to Roermond. Other fields like Local updates were sometimes set and sometimes not (?!)
- After the first sign up a different form appears and when people sign up using that form they're based in Germany (?!)

Can you pls look into this?
Also: It can be that it has been decided that there is a new way of working: If so: please communicate about it. 

Cheers,
Haiko

**Comment by SamLubbers** [comment]
Hi @haikomeelis thank you for opening this issue. There were indeed a few updates to Action Network that we still need to communicate to local groups. One of them is the replacement of tags with `local_group = Roermond`. I will soon reach out to you over Mattermost and explain why this change was made. 

For signing up people after talks, we recommend you use these forms rather than the one on the website:
* English: https://actionnetwork.org/forms/join_xrnl
* Dutch: https://actionnetwork.org/forms/sluit-je-aan-bij-xr-nl

I will close this issue now as it is specifically related to Action Network and not to a change to the website. If you have any more questions please contact [@ActionNetworkSupport](https://organise.earth/xr-netherlands/messages/@actionnetworksupport) on Mattermost.
